language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.2

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-19
    # - sys-img-x86-android-17
sudo: false

jdk:
  - oraclejdk8

env:
  global:
    MALLOC_ARENA_MAX=2
    GRADLE_OPTS=-Xmx1024m -Dorg.gradle.parallel=false

addons:
  apt:
    packages:
      - gzip
      - tar

before_install:
  - openssl aes-256-cbc -K $encrypted_6cd7e6cdc472_key -iv $encrypted_6cd7e6cdc472_iv -in travis/configs/steel_private_config.tgz.enc -out travis/configs/steel_private_config.tgz -d

before_script:
  # Extracts build configs into source tree
  - tar zxf travis/configs/steel_private_config.tar.gz

script: ./gradlew build --no-daemon --stacktrace

deploy:
  provider: releases
  api_key:
    secure: V5ubzw9Ft9SRG2Exq1VfWwmndhso3Qijipb2tPpYdnYhZIj7xQ72jA6RCfdAx0ROe03UP5BxhAtAwl1X/iRPfYcvpsYTKtoXME6wEHfbNZD1FXFHKE9DWd6iU9DIljLUE86AhKp+21lm3YvGDPL1DrkKPfhoejuf8TlOuT3q2l+Q26gtXdon91O7tpj3z/yNCXVoPfytyyzUD9o0fmNjEg5o8DDoTs/+7vLTTiSrGiA/Boe3lz/Qi2S78NL1KmOeeHcRhs06+oVcY+Gtc0QuAUyUhevwXPlMGMmP+DCGYmEIjr7NNlCk3Qo96rXshsvvgX8gw/cozJyplPVY6schlzlnb+cm5E2dk/icTjx/+mTSQan55ovm9z+EKW0t0AEALH0kufcd5Mh3oom2/XOKTJ3udl4PNJDzgwWl4OLYrjRQmTa1f6EWw9ELq9+q8QGwX+V1FhHaS22lS/d33SRQmyQC+FYx2rXpFKx574TwsRJ8lDmQaFHqj+AMA9syTf8SRPlp+glSjE1qt8YohJhW8YJaeqzVmgVJf3qZvbRo76arJro3CW7ntw6fJfccYp8hkiuVei0FGQ29Dn4F2Qg2nxQrEGecW2DwSWIazLrSJOnAZSS3pSPKrOqMnK6b/lOuVMXKA0eyntUGs0N0tFYjLMmi5OnM/wk/Xbl1GNfGhGw=
  file_glob: true
  file: '**/*-release.apk'
  on:
    tags: true
    repo: MobiWorker/Steel
