language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.2

    # The SDK version used to compile your project
    - android-23

    # Additional components

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-19
    # - sys-img-x86-android-17
sudo: false

jdk:
  - oraclejdk8

env:
  global:
    MALLOC_ARENA_MAX=2
    GRADLE_OPTS=-Xmx1024m -Dorg.gradle.parallel=false

addons:
  apt:
    packages:
      - python2.7
      - libmagic1

cache:
  directories:
  - $HOME/.local/opt

before_install:
  - ./travis/scripts/extract_private_build_config.sh
  - export PATH=$HOME/.local/bin:$PATH
  - pip install -r ./travis/configs/requirements.txt --user

script: ./gradlew build --no-daemon --stacktrace

after_success: ./travis/scripts/travis_upload_release_to_github.py
